public class StringArrayTest {
    
    public static List<String> generateStringArray(Integer num){
        integer j = num;
        List<String> list1 = new List<String>();
        for(integer i=0; i<j;i++)
        {
           list1.add('Test '+i);
        }
        return list1;
        
    }
   Account acc = new Account(Name ='Muhammad Usman');
   sObject sobj1 = new  Account (Name ='Muhammad Usman');
   //sObjcet sobj2 = new  Book__c(Name = 'Started With Apexx');

}